name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: mattnite/setup-gyro@v1.0.0
      - uses: actions/checkout@v2
      - run: gyro build test
